import { readFileSync, writeFileSync } from 'node:fs'
import sharp from 'sharp'
import { ICON_LADDER, tileSvg } from './iconLadder.mjs'
import { writeIco } from './icoWriter.mjs'

// Source of truth: the committed brand pack under assets/branding/.
const B = 'assets/branding/notes-and-codes-logo'

// The brand SVGs declare only a viewBox, so sharp scales them by DPI density — and any
// density high enough for crisp small output trips its pixel limit. Give the root an
// explicit pixel size instead, and rasterise once at a comfortable master resolution.
const sized = (svg, w, h) => Buffer.from(svg.replace('<svg ', `<svg width="${w}" height="${h}" `))

const glyphSvg = readFileSync(`${B}/svg/nc-glyph-dark.svg`, 'utf8')

// The ampersand alone is the middle <path> of that same glyph SVG, re-framed to its own
// viewBox — derived from the one source file so there's no second copy to keep in sync.
// Two assumptions about nc-glyph-dark.svg's shape, both baked into the regex/viewBox below:
//   1. `transform` must be the FIRST attribute on that <path> — the regex anchors on
//      `<path transform="translate(600,0)"`. If the source SVG ever reorders attributes,
//      the match fails loudly (thrown error below), so this one is safe.
//   2. The hardcoded `viewBox="600 -920 640 1121"` assumes the glyph's 600-unit advance.
//      If that advance ever changes, this does NOT throw — it silently reframes the
//      ampersand artwork wrongly. This is the more dangerous of the two assumptions.
const ampPath = glyphSvg.match(/<path transform="translate\(600,0\)"[\s\S]*?\/>/)
if (!ampPath) throw new Error('nc-glyph-dark.svg: could not find the ampersand path at translate(600,0)')
const ampSvg =
  '<svg xmlns="http://www.w3.org/2000/svg" viewBox="600 -920 640 1121">' +
  `<g transform="scale(1,-1)">${ampPath[0]}</g></svg>`

// Master rasters, sized to each artwork's own aspect ratio ({&} ≈ 1.763:1, & ≈ 0.571:1).
const MASTER = {
  glyph: sized(glyphSvg, 1024, 623),
  amp: sized(ampSvg, 320, 560)
}

/** One .ico frame: either a composited tile+glyph, or a committed app-icon PNG. */
async function frameFor({ size, art, scale }) {
  if (art === 'tile') return readFileSync(`${B}/app-icon-dark/nc-icon-${size}.png`)

  const glyph = await sharp(MASTER[art])
    .resize({ width: Math.max(1, Math.round(size * scale)), fit: 'inside', kernel: 'lanczos3' })
    .png()
    .toBuffer()
  const { width, height } = await sharp(glyph).metadata()

  return sharp(Buffer.from(tileSvg(size)))
    .composite([{ input: glyph, left: Math.round((size - width) / 2), top: Math.round((size - height) / 2) }])
    .png({ compressionLevel: 9 })
    .toBuffer()
}

// build/icon.ico — the identity icon: stamped onto the exe and the installed shortcut by
// electron-builder, and therefore what the taskbar button, Alt+Tab and Explorer show. The
// full {N&C} mark is illegible below ~48px, so the small frames carry {&} instead.
const frames = []
for (const entry of ICON_LADDER) frames.push({ size: entry.size, png: await frameFor(entry) })
writeFileSync('build/icon.ico', writeIco(frames))

// src/main/trayImage.ts — both tray glyphs as base64 so the tray can swap to contrast with
// a light or dark taskbar at runtime (see tray.ts). Padded to square 32x32: the committed
// glyphs are 32x19, and both Tray and BrowserWindow.setIcon expect a square image.
const squareGlyph = async (path) =>
  (
    await sharp(readFileSync(path))
      .resize({ width: 32, height: 32, fit: 'contain', background: { r: 0, g: 0, b: 0, alpha: 0 } })
      .png({ compressionLevel: 9 })
      .toBuffer()
  ).toString('base64')

const darkBg = await squareGlyph(`${B}/tray/nc-tray-for-dark-bg-32.png`)   // bright glyph, dark taskbar
const lightBg = await squareGlyph(`${B}/tray/nc-tray-for-light-bg-32.png`) // dark glyph, light taskbar
writeFileSync(
  'src/main/trayImage.ts',
  '// generated by scripts/make-icon.mjs — do not edit\n' +
    `export const TRAY_PNG_DARK_BG_BASE64 = '${darkBg}'\n` +
    `export const TRAY_PNG_LIGHT_BG_BASE64 = '${lightBg}'\n`
)

console.log(
  `wrote build/icon.ico (${frames.map((f) => f.size).join('/')}, {&} below 48) ` +
    'and src/main/trayImage.ts (square 32x32 light + dark tray glyphs)'
)
