import { readFileSync, writeFileSync, copyFileSync } from 'node:fs'

// Source of truth: the committed brand pack under assets/branding/.
// App icon = the DARK app-icon (self-contained rounded tile, legible on any
// background). Tray = the purpose-built small glyphs, one per taskbar theme.
const B = 'assets/branding/notes-and-codes-logo'

// build/icon.ico — the prebuilt dark .ico export (used by electron-builder for the
// exe / installer / taskbar icon). Copied verbatim: it's already an optimised
// multi-size icon (PNG-compressed 256px), so we don't re-encode it.
copyFileSync(`${B}/ico/notes-and-codes-dark.ico`, 'build/icon.ico')

// src/main/trayImage.ts — both 32px tray glyphs as base64 so the tray can swap
// to contrast with a light or dark taskbar at runtime (see tray.ts).
const darkBg = readFileSync(`${B}/tray/nc-tray-for-dark-bg-32.png`).toString('base64')   // bright glyph, dark taskbar
const lightBg = readFileSync(`${B}/tray/nc-tray-for-light-bg-32.png`).toString('base64') // dark glyph, light taskbar
writeFileSync('src/main/trayImage.ts',
  '// generated by scripts/make-icon.mjs — do not edit\n' +
  `export const TRAY_PNG_DARK_BG_BASE64 = '${darkBg}'\n` +
  `export const TRAY_PNG_LIGHT_BG_BASE64 = '${lightBg}'\n`)

console.log('wrote build/icon.ico (dark app-icon) and src/main/trayImage.ts (light + dark tray glyphs)')
