import sharp from 'sharp'
import pngToIco from 'png-to-ico'
import { readFileSync, writeFileSync } from 'node:fs'

const svg = readFileSync('build/icon.svg')
const sizes = [16, 24, 32, 48, 64, 128, 256]
const pngs = await Promise.all(sizes.map(s => sharp(svg).resize(s, s).png().toBuffer()))
writeFileSync('build/icon.ico', await pngToIco(pngs))
const tray = await sharp(svg).resize(32, 32).png().toBuffer()
writeFileSync('src/main/trayImage.ts', `// generated by scripts/make-icon.mjs — do not edit\nexport const TRAY_PNG_BASE64 = '${tray.toString('base64')}'\n`)
console.log('wrote build/icon.ico and src/main/trayImage.ts')
